version: "3.9"

services:
  django:
    # Name of container (for docker ps/docker-compose ps)
    container_name: ...
    # ENV variables for docker-compose container
    env_file:
    - ...
    # Dev environment need changes to be refected immediately
    volumes:
    - ...
    # Dev environment can be accessed from anywhere
    ports:
    - ...
    # Whether container restart when error occurs (always, unless-stop)
    restart: ...

services2:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: