# Generated by Django 3.2.13 on 2022-05-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='social',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
        ),
    ]
